### PR TITLE
Add missing field `tokens` to initializers of `syntax::ast::Item`

### LINKED ISSUE #85: Compiler error from Stainless library on OSX 10.12.6
```Attempting to use Stainless for integration testing. Rust compiler complains:

Compiling stainless v0.1.11
error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jimdandy/.cargo/registry/src/github.com-1ecc6299db9ec823/stainless-0.1.11/src/generate.rs:113:11
    |
113 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`

error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jimdandy/.cargo/registry/src/github.com-1ecc6299db9ec823/stainless-0.1.11/src/generate.rs:149:11
    |
149 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`

error: aborting due to 2 previous errors

error: Could not compile `stainless`.
```

### PR DESCRIPTION
**Pull request by neverfox**
Fixes #85

### CODE REVIEW

**Comment by hatzel** [comment]
Would greatly appreciate this being merged! Looks like a correct fix to me!

**Comment by svenstaro** [comment]
Hey @reem can you look into this?

**Comment by ujh** [comment]
Sorry for the delay! I just tried to run the tests with `rustc 1.22.0-nightly (d7e73e4b1 2017-10-04)` and it worked. Could you please have a look if it's still broken?

**Comment by ujh** [comment]
Never mind, I compiled the wrong project. 😂

**Comment by ujh** [comment]
Thank you for the fix!

**Pull request merged**
