### PR TITLE
Add MIT license and license headers

### PR DESCRIPTION
**Pull request by ujh**
I went through the whole commit history and added everyone who contributed even a single line to the license headers. Everyone is now also in the cargo file. The ordering of the names in the headers is somewhat random, I just added the name whenever I found it. That is apart from @reem. :) He's first whenever he contributed in a given name. And in the cargo file the names are sorted alphabetically. Again apart from Jonathan.

### CODE REVIEW

**Comment by reem** [comment]
Hmm, while this is nice I think it is probably going to be very difficult to maintain accurately in the long run, maybe it would be better to just say 'The Stainless Developers' or something?

**Comment by ujh** [comment]
Somehow I thought that you needed to list every author in every file. But you're right, listing them in Cargo.toml and mentioning that file in the header should be enough.

**Comment by ujh** [comment]
I've updated the PR and it now just mentions "The Stainless Developers" in each file header.

**Comment by utkarshkukreti** [comment]
Is it really necessary to add the complete license text on top of every file? Rust, for example adds a 3 line copyright and 5 line mention of the 2 licenses the users can choose from: https://github.com/rust-lang/rust/blob/34505e22289d3b2416ab0922131e8526d0d5cc0b/src/libcore/any.rs#L1-L9.

**Comment by ujh** [comment]
Who would have thought that adding license headers would lead to so much discussion. 😆 But it's great that it's now only 5 lines. 👍

**Pull request merged**
